app_admin_product_type:
    resource: |
        alias: sylius_mollie.product_type
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        grid: sylius_mollie_plugin_admin_product_type
        vars:
            all:
                subheader: sylius_mollie.ui.manage_product_types
        redirect: index
        permission: true
    type: sylius.resource
